<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $all_countries = '[
	{
		"capital": "Vienna",
		"citizenship": "Austrian",
		"country_code": "040",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Republic of Austria",
		"iso_3166_2": "AT",
		"iso_3166_3": "AUT",
		"name": "Austria",
		"region_code": "150",
		"sub_region_code": "155",
		"eea": 1,
		"calling_code": "43",
		"flag": "AT.png"
	},
	{
		"capital": "Brussels",
		"citizenship": "Belgian",
		"country_code": "056",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Kingdom of Belgium",
		"iso_3166_2": "BE",
		"iso_3166_3": "BEL",
		"name": "Belgium",
		"region_code": "150",
		"sub_region_code": "155",
		"eea": 1,
		"calling_code": "32",
		"flag": "BE.png"
	},
	{
		"capital": "Sarajevo",
		"citizenship": "of Bosnia and Herzegovina",
		"country_code": "070",
		"currency": "convertible mark",
		"currency_code": "BAM",
		"currency_sub_unit": "fening",
		"currency_symbol": "KM",
		"full_name": "Bosnia and Herzegovina",
		"iso_3166_2": "BA",
		"iso_3166_3": "BIH",
		"name": "Bosnia and Herzegovina",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 0,
		"calling_code": "387",
		"flag": "BA.png"
	},
	{
		"capital": "Sofia",
		"citizenship": "Bulgarian",
		"country_code": "100",
		"currency": "lev (pl. leva)",
		"currency_code": "BGN",
		"currency_sub_unit": "stotinka",
		"currency_symbol": "Ð»Ð²",
		"full_name": "Republic of Bulgaria",
		"iso_3166_2": "BG",
		"iso_3166_3": "BGR",
		"name": "Bulgaria",
		"region_code": "150",
		"sub_region_code": "151",
		"eea": 1,
		"calling_code": "359",
		"flag": "BG.png"
	},
	{
		"capital": "Minsk",
		"citizenship": "Belarusian",
		"country_code": "112",
		"currency": "Belarusian rouble",
		"currency_code": "BYR",
		"currency_sub_unit": "kopek",
		"currency_symbol": "p.",
		"full_name": "Republic of Belarus",
		"iso_3166_2": "BY",
		"iso_3166_3": "BLR",
		"name": "Belarus",
		"region_code": "150",
		"sub_region_code": "151",
		"eea": 0,
		"calling_code": "375",
		"flag": "BY.png"
	},
	{
		"capital": "Zagreb",
		"citizenship": "Croatian",
		"country_code": "191",
		"currency": "kuna (inv.)",
		"currency_code": "HRK",
		"currency_sub_unit": "lipa (inv.)",
		"currency_symbol": "kn",
		"full_name": "Republic of Croatia",
		"iso_3166_2": "HR",
		"iso_3166_3": "HRV",
		"name": "Croatia",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 1,
		"calling_code": "385",
		"flag": "HR.png"
	},
	{
		"capital": "Nicosia",
		"citizenship": "Cypriot",
		"country_code": "196",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "CYP",
		"full_name": "Republic of Cyprus",
		"iso_3166_2": "CY",
		"iso_3166_3": "CYP",
		"name": "Cyprus",
		"region_code": "142",
		"sub_region_code": "145",
		"eea": 1,
		"calling_code": "357",
		"flag": "CY.png"
	},
	{
		"capital": "Prague",
		"citizenship": "Czech",
		"country_code": "203",
		"currency": "Czech koruna (pl. koruny)",
		"currency_code": "CZK",
		"currency_sub_unit": "halÃ©r",
		"currency_symbol": "KÄ",
		"full_name": "Czech Republic",
		"iso_3166_2": "CZ",
		"iso_3166_3": "CZE",
		"name": "Czech Republic",
		"region_code": "150",
		"sub_region_code": "151",
		"eea": 1,
		"calling_code": "420",
		"flag": "CZ.png"
	},
	{
		"capital": "Copenhagen",
		"citizenship": "Danish",
		"country_code": "208",
		"currency": "Danish krone",
		"currency_code": "DKK",
		"currency_sub_unit": "Ã¸re (inv.)",
		"currency_symbol": "kr",
		"full_name": "Kingdom of Denmark",
		"iso_3166_2": "DK",
		"iso_3166_3": "DNK",
		"name": "Denmark",
		"region_code": "150",
		"sub_region_code": "154",
		"eea": 1,
		"calling_code": "45",
		"flag": "DK.png"
	},
	{
		"capital": "Tallinn",
		"citizenship": "Estonian",
		"country_code": "233",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "kr",
		"full_name": "Republic of Estonia",
		"iso_3166_2": "EE",
		"iso_3166_3": "EST",
		"name": "Estonia",
		"region_code": "150",
		"sub_region_code": "154",
		"eea": 1,
		"calling_code": "372",
		"flag": "EE.png"
	},
	{
		"capital": "Helsinki",
		"citizenship": "Finnish",
		"country_code": "246",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Republic of Finland",
		"iso_3166_2": "FI",
		"iso_3166_3": "FIN",
		"name": "Finland",
		"region_code": "150",
		"sub_region_code": "154",
		"eea": 1,
		"calling_code": "358",
		"flag": "FI.png"
	},
	{
		"capital": "Paris",
		"citizenship": "French",
		"country_code": "250",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "French Republic",
		"iso_3166_2": "FR",
		"iso_3166_3": "FRA",
		"name": "France",
		"region_code": "150",
		"sub_region_code": "155",
		"eea": 1,
		"calling_code": "33",
		"flag": "FR.png"
	},
	{
		"capital": "Berlin",
		"citizenship": "German",
		"country_code": "276",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Federal Republic of Germany",
		"iso_3166_2": "DE",
		"iso_3166_3": "DEU",
		"name": "Germany",
		"region_code": "150",
		"sub_region_code": "155",
		"eea": 1,
		"calling_code": "49",
		"flag": "DE.png"
	},
	{
		"capital": "Athens",
		"citizenship": "Greek",
		"country_code": "300",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Hellenic Republic",
		"iso_3166_2": "GR",
		"iso_3166_3": "GRC",
		"name": "Greece",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 1,
		"calling_code": "30",
		"flag": "GR.png"
	},
	{
		"capital": "Vatican City",
		"citizenship": "of the Holy See/of the Vatican",
		"country_code": "336",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "the Holy See/ Vatican City State",
		"iso_3166_2": "VA",
		"iso_3166_3": "VAT",
		"name": "Holy See (Vatican City State)",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 0,
		"calling_code": "39",
		"flag": "VA.png"
	},
	{
		"capital": "Budapest",
		"citizenship": "Hungarian",
		"country_code": "348",
		"currency": "forint (inv.)",
		"currency_code": "HUF",
		"currency_sub_unit": "(fillÃ©r (inv.))",
		"currency_symbol": "Ft",
		"full_name": "Republic of Hungary",
		"iso_3166_2": "HU",
		"iso_3166_3": "HUN",
		"name": "Hungary",
		"region_code": "150",
		"sub_region_code": "151",
		"eea": 1,
		"calling_code": "36",
		"flag": "HU.png"
	},
	{
		"capital": "Reykjavik",
		"citizenship": "Icelander",
		"country_code": "352",
		"currency": "krÃ³na (pl. krÃ³nur)",
		"currency_code": "ISK",
		"currency_sub_unit": "",
		"currency_symbol": "kr",
		"full_name": "Republic of Iceland",
		"iso_3166_2": "IS",
		"iso_3166_3": "ISL",
		"name": "Iceland",
		"region_code": "150",
		"sub_region_code": "154",
		"eea": 1,
		"calling_code": "354",
		"flag": "IS.png"
	},
	{
		"capital": "Dublin",
		"citizenship": "Irish",
		"country_code": "372",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Ireland (IE1)",
		"iso_3166_2": "IE",
		"iso_3166_3": "IRL",
		"name": "Ireland",
		"region_code": "150",
		"sub_region_code": "154",
		"eea": 1,
		"calling_code": "353",
		"flag": "IE.png"
	},
	{
		"capital": "Rome",
		"citizenship": "Italian",
		"country_code": "380",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Italian Republic",
		"iso_3166_2": "IT",
		"iso_3166_3": "ITA",
		"name": "Italy",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 1,
		"calling_code": "39",
		"flag": "IT.png"
	},
	{
		"capital": "Riga",
		"citizenship": "Latvian",
		"country_code": "428",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "Ls",
		"full_name": "Republic of Latvia",
		"iso_3166_2": "LV",
		"iso_3166_3": "LVA",
		"name": "Latvia",
		"region_code": "150",
		"sub_region_code": "154",
		"eea": 1,
		"calling_code": "371",
		"flag": "LV.png"
	},
	{
		"capital": "Vaduz",
		"citizenship": "Liechtensteiner",
		"country_code": "438",
		"currency": "Swiss franc",
		"currency_code": "CHF",
		"currency_sub_unit": "centime",
		"currency_symbol": "CHF",
		"full_name": "Principality of Liechtenstein",
		"iso_3166_2": "LI",
		"iso_3166_3": "LIE",
		"name": "Liechtenstein",
		"region_code": "150",
		"sub_region_code": "155",
		"eea": 1,
		"calling_code": "423",
		"flag": "LI.png"
	},
	{
		"capital": "Vilnius",
		"citizenship": "Lithuanian",
		"country_code": "440",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "Lt",
		"full_name": "Republic of Lithuania",
		"iso_3166_2": "LT",
		"iso_3166_3": "LTU",
		"name": "Lithuania",
		"region_code": "150",
		"sub_region_code": "154",
		"eea": 1,
		"calling_code": "370",
		"flag": "LT.png"
	},
	{
		"capital": "Luxembourg",
		"citizenship": "Luxembourger",
		"country_code": "442",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Grand Duchy of Luxembourg",
		"iso_3166_2": "LU",
		"iso_3166_3": "LUX",
		"name": "Luxembourg",
		"region_code": "150",
		"sub_region_code": "155",
		"eea": 1,
		"calling_code": "352",
		"flag": "LU.png"
	},
	{
		"capital": "Valletta",
		"citizenship": "Maltese",
		"country_code": "470",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "MTL",
		"full_name": "Republic of Malta",
		"iso_3166_2": "MT",
		"iso_3166_3": "MLT",
		"name": "Malta",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 1,
		"calling_code": "356",
		"flag": "MT.png"
	},
	{
		"capital": "Monaco",
		"citizenship": "Monegasque",
		"country_code": "492",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Principality of Monaco",
		"iso_3166_2": "MC",
		"iso_3166_3": "MCO",
		"name": "Monaco",
		"region_code": "150",
		"sub_region_code": "155",
		"eea": 0,
		"calling_code": "377",
		"flag": "MC.png"
	},
	{
		"capital": "Chisinau",
		"citizenship": "Moldovan",
		"country_code": "498",
		"currency": "Moldovan leu (pl. lei)",
		"currency_code": "MDL",
		"currency_sub_unit": "ban",
		"currency_symbol": "MDL",
		"full_name": "Republic of Moldova",
		"iso_3166_2": "MD",
		"iso_3166_3": "MDA",
		"name": "Moldova, Republic of",
		"region_code": "150",
		"sub_region_code": "151",
		"eea": 0,
		"calling_code": "373",
		"flag": "MD.png"
	},
	{
		"capital": "Podgorica",
		"citizenship": "Montenegrin",
		"country_code": "499",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": null,
		"full_name": "Montenegro",
		"iso_3166_2": "ME",
		"iso_3166_3": "MNE",
		"name": "Montenegro",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 0,
		"calling_code": "382",
		"flag": null
	},
	{
		"capital": "Amsterdam (NL2)",
		"citizenship": "Dutch",
		"country_code": "528",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Kingdom of the Netherlands",
		"iso_3166_2": "NL",
		"iso_3166_3": "NLD",
		"name": "Netherlands",
		"region_code": "150",
		"sub_region_code": "155",
		"eea": 1,
		"calling_code": "31",
		"flag": "NL.png"
	},
	{
		"capital": "Oslo",
		"citizenship": "Norwegian",
		"country_code": "578",
		"currency": "Norwegian krone (pl. kroner)",
		"currency_code": "NOK",
		"currency_sub_unit": "Ã¸re (inv.)",
		"currency_symbol": "kr",
		"full_name": "Kingdom of Norway",
		"iso_3166_2": "NO",
		"iso_3166_3": "NOR",
		"name": "Norway",
		"region_code": "150",
		"sub_region_code": "154",
		"eea": 1,
		"calling_code": "47",
		"flag": "NO.png"
	},
	{
		"capital": "Warsaw",
		"citizenship": "Polish",
		"country_code": "616",
		"currency": "zloty",
		"currency_code": "PLN",
		"currency_sub_unit": "grosz (pl. groszy)",
		"currency_symbol": "zÅ‚",
		"full_name": "Republic of Poland",
		"iso_3166_2": "PL",
		"iso_3166_3": "POL",
		"name": "Poland",
		"region_code": "150",
		"sub_region_code": "151",
		"eea": 1,
		"calling_code": "48",
		"flag": "PL.png"
	},
	{
		"capital": "Lisbon",
		"citizenship": "Portuguese",
		"country_code": "620",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Portuguese Republic",
		"iso_3166_2": "PT",
		"iso_3166_3": "PRT",
		"name": "Portugal",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 1,
		"calling_code": "351",
		"flag": "PT.png"
	},
	{
		"capital": "Bucharest",
		"citizenship": "Romanian",
		"country_code": "642",
		"currency": "Romanian leu (pl. lei)",
		"currency_code": "RON",
		"currency_sub_unit": "ban (pl. bani)",
		"currency_symbol": "lei",
		"full_name": "Romania",
		"iso_3166_2": "RO",
		"iso_3166_3": "ROU",
		"name": "Romania",
		"region_code": "150",
		"sub_region_code": "151",
		"eea": 1,
		"calling_code": "40",
		"flag": "RO.png"
	},
	{
		"capital": "Moscow",
		"citizenship": "Russian",
		"country_code": "643",
		"currency": "Russian rouble",
		"currency_code": "RUB",
		"currency_sub_unit": "kopek",
		"currency_symbol": "Ñ€ÑƒÐ±",
		"full_name": "Russian Federation",
		"iso_3166_2": "RU",
		"iso_3166_3": "RUS",
		"name": "Russian Federation",
		"region_code": "150",
		"sub_region_code": "151",
		"eea": 0,
		"calling_code": "7",
		"flag": "RU.png"
	},
	{
		"capital": "San Marino",
		"citizenship": "San Marinese",
		"country_code": "674",
		"currency": "euro",
		"currency_code": "EUR ",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Republic of San Marino",
		"iso_3166_2": "SM",
		"iso_3166_3": "SMR",
		"name": "San Marino",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 0,
		"calling_code": "378",
		"flag": "SM.png"
	},
	{
		"capital": "Belgrade",
		"citizenship": "Serb",
		"country_code": "688",
		"currency": "Serbian dinar",
		"currency_code": "RSD",
		"currency_sub_unit": "para (inv.)",
		"currency_symbol": null,
		"full_name": "Republic of Serbia",
		"iso_3166_2": "RS",
		"iso_3166_3": "SRB",
		"name": "Serbia",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 0,
		"calling_code": "381",
		"flag": null
	},
	{
		"capital": "Bratislava",
		"citizenship": "Slovak",
		"country_code": "703",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "Sk",
		"full_name": "Slovak Republic",
		"iso_3166_2": "SK",
		"iso_3166_3": "SVK",
		"name": "Slovakia",
		"region_code": "150",
		"sub_region_code": "151",
		"eea": 1,
		"calling_code": "421",
		"flag": "SK.png"
	},
	{
		"capital": "Ljubljana",
		"citizenship": "Slovene",
		"country_code": "705",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Republic of Slovenia",
		"iso_3166_2": "SI",
		"iso_3166_3": "SVN",
		"name": "Slovenia",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 1,
		"calling_code": "386",
		"flag": "SI.png"
	},
	{
		"capital": "Madrid",
		"citizenship": "Spaniard",
		"country_code": "724",
		"currency": "euro",
		"currency_code": "EUR",
		"currency_sub_unit": "cent",
		"currency_symbol": "â‚¬",
		"full_name": "Kingdom of Spain",
		"iso_3166_2": "ES",
		"iso_3166_3": "ESP",
		"name": "Spain",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 1,
		"calling_code": "34",
		"flag": "ES.png"
	},
	{
		"capital": "Stockholm",
		"citizenship": "Swedish",
		"country_code": "752",
		"currency": "krona (pl. kronor)",
		"currency_code": "SEK",
		"currency_sub_unit": "Ã¶re (inv.)",
		"currency_symbol": "kr",
		"full_name": "Kingdom of Sweden",
		"iso_3166_2": "SE",
		"iso_3166_3": "SWE",
		"name": "Sweden",
		"region_code": "150",
		"sub_region_code": "154",
		"eea": 1,
		"calling_code": "46",
		"flag": "SE.png"
	},
	{
		"capital": "Berne",
		"citizenship": "Swiss",
		"country_code": "756",
		"currency": "Swiss franc",
		"currency_code": "CHF",
		"currency_sub_unit": "centime",
		"currency_symbol": "CHF",
		"full_name": "Swiss Confederation",
		"iso_3166_2": "CH",
		"iso_3166_3": "CHE",
		"name": "Switzerland",
		"region_code": "150",
		"sub_region_code": "155",
		"eea": 1,
		"calling_code": "41",
		"flag": "CH.png"
	},
	{
		"capital": "Ankara",
		"citizenship": "Turk",
		"country_code": "792",
		"currency": "Turkish lira (inv.)",
		"currency_code": "TRY",
		"currency_sub_unit": "kurus (inv.)",
		"currency_symbol": "â‚º",
		"full_name": "Republic of Turkey",
		"iso_3166_2": "TR",
		"iso_3166_3": "TUR",
		"name": "Turkey",
		"region_code": "142",
		"sub_region_code": "145",
		"eea": 0,
		"calling_code": "90",
		"flag": "TR.png"
	},
	{
		"capital": "Kiev",
		"citizenship": "Ukrainian",
		"country_code": "804",
		"currency": "hryvnia",
		"currency_code": "UAH",
		"currency_sub_unit": "kopiyka",
		"currency_symbol": "â‚´",
		"full_name": "Ukraine",
		"iso_3166_2": "UA",
		"iso_3166_3": "UKR",
		"name": "Ukraine",
		"region_code": "150",
		"sub_region_code": "151",
		"eea": 0,
		"calling_code": "380",
		"flag": "UA.png"
	},
	{
		"capital": "Skopje",
		"citizenship": "of Macedonia",
		"country_code": "807",
		"currency": "denar (pl. denars)",
		"currency_code": "MKD",
		"currency_sub_unit": "deni (inv.)",
		"currency_symbol": "Ð´ÐµÐ½",
		"full_name": "Republic of Macedonia",
		"iso_3166_2": "MK",
		"iso_3166_3": "MKD",
		"name": "Macedonia",
		"region_code": "150",
		"sub_region_code": "039",
		"eea": 0,
		"calling_code": "389",
		"flag": "MK.png"
	}
]';

        //Empty the countries table
        DB::table("countries")->delete();
        DB::statement("ALTER TABLE countries AUTO_INCREMENT = 1;");


        //Get all of the countries
        $countries = json_decode($all_countries, true);

        foreach ($countries as $c) {
            $country = new Country();
            $country->capital = $c["capital"];
            $country->citizenship = $c["citizenship"];
            $country->country_code = $c["country_code"];
            $country->currency_sub_unit = $c["currency_sub_unit"];
            $country->currency_symbol = $c["currency_symbol"];
            $country->full_name = $c["full_name"];
            $country->iso_3166_2 = $c["iso_3166_2"];
            $country->iso_3166_3 = $c["iso_3166_3"];
            $country->name = $c["name"];
            $country->region_code = $c["region_code"];
            $country->sub_region_code = $c["sub_region_code"];
            $country->eea = $c["eea"];
            $country->calling_code = $c["calling_code"];
            $country->flag = $c["flag"];
            $country->save();
        }

    }

}
